####################################
# This file can be used with Skaffold (https://github.com/GoogleContainerTools/skaffold) to
# build and deploy Fission to Kubernetes cluster.
#
############## Usage ##############
# This needs Skaffold installed on your development machine. You can run `skaffold run` to build
# and deploy with helm. For building and pushing images, you can use `skaffold build`
# If certain parts of code don't change - you can comment build for those images (For ex. preupgradechecks)
# Limitations:
# 1) Currently there is a issue with helm tags in Skaffold - so imageTag etc. does not work.
####################################
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
    - image: vishalbiyani/fission
      context: .
      docker:
        dockerfile: Dockerfile.fission-bundle
    - image: vishalbiyani/fetcher
      context: environments/fetcher/cmd
      docker:
        dockerfile: Dockerfile.fission-fetcher
    - image: vishalbiyani/builder
      context: builder
      docker:
        dockerfile: Dockerfile.fission-builder
    - image: vishalbiyani/preupgradechecks
      context: preupgradechecks
      docker:
        dockerfile: Dockerfile.fission-preupgradechecks                
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
      timezone: Local
deploy:
  helm:
    releases:
      - name: fission
        chartPath: ./charts/fission-all
        valuesFiles:
          - ./charts/fission-all/values.yaml
        namespace: "fission"
#        version: ""
        setValues:
          fetcherImage: vishalbiyani/fetcher
          image: vishalbiyani/fission
          imageTag: latest
          namespace: fission
          preUpgradeChecksImage: vishalbiyani/preupgradechecks
        setValueTemplates: {}
        wait: true
        recreatePods: false
        overrides: {}
        packaged: null
        imageStrategy:
          fqn: null
          helm: null
